---
version: '3'

services:
  docker-registry:
    container_name: docker-registry-a
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./volume:/var/lib/registry
  docker-registry-ui:
    container_name: docker-registry-ui-a
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8080:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry-a
      ENV_DOCKER_REGISTRY_PORT: 5000

